apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: skge217cm-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: skge217cm-go 
  name: skge217cm-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: skge217cm-go 
